# Generated by Django 4.2.30 on 2026-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homebase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.CharField()),
                ('country', models.CharField()),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
