# Generated by Django 4.2.30 on 2026-10-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebase',
            name='banner',
            field=models.CharField(default='banner_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homebase',
            name='city',
            field=models.CharField(default='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='country',
            field=models.CharField(default='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='name',
            field=models.CharField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='state',
            field=models.CharField(default='state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='street_address',
            field=models.CharField(default='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebase',
            name='zipcode',
            field=models.CharField(default='zipcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homebase',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
