# Generated by Django 4.2.30 on 2026-10-04 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebase', '0002_homebase_banner_homebase_bio_homebase_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebase',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
