# Generated by Django 4.2.30 on 2026-10-06 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebase', '0003_homebase_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='homebase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rentals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homebase.rental')),
            ],
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('rent', models.FloatField()),
                ('homebase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.homebase')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='subproperty_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homebase.subproperty'),
        ),
        migrations.CreateModel(
            name='OwnedProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField()),
                ('owner_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homebase.propertyowner')),
                ('subproperty_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homebase.subproperty')),
            ],
        ),
    ]
