# Generated by Django 4.2.30 on 2026-10-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebase', '0004_propertymanager_propertyowner_rental_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='rentals',
            new_name='rents',
        ),
        migrations.RemoveField(
            model_name='ownedproperty',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='homebase',
            name='managed_by',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='homebase.propertymanager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='owns',
            field=models.ManyToManyField(to='homebase.ownedproperty'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='subproperty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.subproperty'),
        ),
        migrations.RemoveField(
            model_name='subproperty',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='subproperty',
            name='managed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
