# Generated by Django 4.2.30 on 2026-10-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0005_rename_rentals_tenant_rents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebase',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='managed_homebases',
            field=models.ManyToManyField(blank=True, null=True, to='homebase.homebase'),
        ),
    ]
