# Generated by Django 4.2.30 on 2026-10-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0006_remove_homebase_managed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='owns',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='rents',
            new_name='rental',
        ),
        migrations.RemoveField(
            model_name='ownedproperty',
            name='end_date',
        ),
        migrations.DeleteModel(
            name='PropertyManager',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.AddField(
            model_name='homebase',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, to='homebase.manager'),
        ),
        migrations.AddField(
            model_name='ownedproperty',
            name='owners',
            field=models.ManyToManyField(to='homebase.owner'),
        ),
    ]
