# Generated by Django 4.2.30 on 2026-10-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0007_manager_owner_remove_propertyowner_owns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproperty',
            name='rent',
        ),
        migrations.AddField(
            model_name='rental',
            name='rent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homebase',
            name='banner',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='managers',
            field=models.ManyToManyField(to='homebase.manager'),
        ),
    ]
