# Generated by Django 4.2.30 on 2026-10-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0009_remove_manager_user_id_remove_owner_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedproperty',
            old_name='subproperty_id',
            new_name='subproperty',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='subproperty_id',
            new_name='subproperty',
        ),
        migrations.RenameField(
            model_name='subproperty',
            old_name='homebase_id',
            new_name='homebase',
        ),
    ]
