# Generated by Django 4.2.30 on 2026-10-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0010_rename_subproperty_id_ownedproperty_subproperty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproperty',
            old_name='number',
            new_name='room_number',
        ),
    ]
