# Generated by Django 4.2.30 on 2026-10-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0011_rename_number_subproperty_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='user',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='user',
            new_name='tenant',
        ),
    ]
