# Generated by Django 4.2.30 on 2026-10-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tenant_owner_manager'),
        ('homebase', '0012_rename_user_manager_manager_rename_user_owner_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant',
        ),
        migrations.AddField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='homebase',
            name='managers',
            field=models.ManyToManyField(to='users.manager'),
        ),
        migrations.AlterField(
            model_name='ownedproperty',
            name='owners',
            field=models.ManyToManyField(to='users.owner'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
