# Generated by Django 6.1.1 on 2026-10-10 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0013_remove_owner_owner_remove_tenant_rental_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedproperty',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AddField(
            model_name='subproperty',
            name='classification',
            field=models.CharField(choices=[('rental', 'Rental'), ('owned', 'Owned')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproperty',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
