# Generated by Django 4.2.30 on 2026-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0013_remove_owner_owner_remove_tenant_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='occupied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
