# Generated by Django 4.2.30 on 2026-10-07 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebase', '0013_remove_owner_owner_remove_tenant_rental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('date', models.DateField()),
                ('location', models.CharField()),
                ('body', models.TextField()),
                ('post_to', models.CharField(choices=[('public', 'Public'), ('homebase', 'Homebase')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('homebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homebase.homebase')),
            ],
        ),
    ]
