# Generated by Django 4.2.30 on 2026-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.CharField(default='photo_url'),
            preserve_default=False,
        ),
    ]
