# Generated by Django 4.2.30 on 2026-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_homebase_banner_homebase_bio_homebase_city_and_more'),
        ('users', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homebases',
            field=models.ManyToManyField(to='homebase.homebase'),
        ),
    ]
