# Generated by Django 4.2.30 on 2026-10-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_homebases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='homebases',
        ),
    ]
