# Generated by Django 4.2.30 on 2026-10-04 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_homebase_banner_homebase_bio_homebase_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_remove_profile_homebases'),
    ]

    operations = [
        migrations.CreateModel(
            name='relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homebases', models.ManyToManyField(blank=True, to='homebase.homebase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
