# Generated by Django 4.2.30 on 2026-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
