# Generated by Django 4.2.30 on 2026-10-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_relations_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relations',
        ),
    ]
