# Generated by Django 4.2.30 on 2026-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tenant_propertyowners_propertymanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='propertymanager',
            name='user',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='PropertyOwners',
        ),
    ]
