# Generated by Django 4.2.30 on 2026-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_propertyowner_alter_propertymanager_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanager',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.IntegerField(),
        ),
    ]
