# Generated by Django 4.2.30 on 2026-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_propertymanager_user_alter_propertyowner_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanager',
            name='id',
        ),
        migrations.RemoveField(
            model_name='propertymanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='user_id',
            field=models.IntegerField(default='-1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='user_id',
            field=models.IntegerField(default='-1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='user_id',
            field=models.IntegerField(default='-1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
