# Generated by Django 4.2.30 on 2026-10-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_propertymanager_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyManager',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
