# Generated by Django 4.2.30 on 2026-10-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('body', models.TextField()),
                ('catagory', models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('marketplace', 'Marketplace')])),
                ('post_to', models.CharField(choices=[('homebase', 'Homebase'), ('public', 'Public')])),
                ('image', models.CharField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
