# Generated by Django 4.2.30 on 2026-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('body', models.TextField()),
                ('status', models.CharField()),
                ('catagory', models.CharField()),
                ('postTo', models.CharField()),
                ('image', models.CharField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
