# Generated by Django 4.2.30 on 2026-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('public', 'Public'), ('homebase', 'Homebase')]),
        ),
    ]
