# Generated by Django 4.2.30 on 2026-09-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postTo',
            new_name='post_to',
        ),
    ]
