# Generated by Django 4.2.30 on 2026-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('marketplace', 'Marketplace')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('public', 'Public'), ('homebase', 'Homebase')]),
        ),
    ]
