# Generated by Django 4.2.30 on 2026-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_updated_at_alter_post_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('homebase', 'Homebase'), ('public', 'Public')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
