# Generated by Django 4.2.30 on 2026-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_deleted_alter_post_image_alter_post_post_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('marketplace', 'Marketplace'), ('announcement', 'Announcement')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('public', 'Public'), ('homebase', 'Homebase')]),
        ),
    ]
