# Generated by Django 4.2.30 on 2026-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_catagory_alter_post_post_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('homebase', 'Homebase'), ('public', 'Public')]),
        ),
    ]
