# Generated by Django 4.2.30 on 2026-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_post_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('marketplace', 'Marketplace')]),
        ),
    ]
