# Generated by Django 6.1.1 on 2026-10-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_post_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('marketplace', 'Marketplace'), ('announcement', 'Announcement')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('homebase', 'Homebase'), ('public', 'Public')]),
        ),
    ]
