# Generated by Django 4.2.30 on 2026-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_post_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('marketplace', 'Marketplace')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to',
            field=models.CharField(choices=[('homebase', 'Homebase'), ('public', 'Public')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True),
        ),
    ]
