# Generated by Django 4.2.30 on 2026-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_catagory_alter_post_post_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('marketplace', 'Marketplace'), ('announcement', 'Announcement')]),
        ),
    ]
